/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: Empty Application
*              Template for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_gpio.h"
#include "xmc_uart.h"
#include "cycfg_peripherals.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "retarget_io.h"

#include "bms.h"
#include "bms_wifi.h"
#include "mempool.h"
#include "bms_soc.h"

#include "bms_code_eval.h"

/*******************************************************************************
* Defines
*******************************************************************************/

#define TICKS_PER_SECOND        1000

static void bms_board_tick_init(void)
{
    NVIC_SetPriority(CCU40_3_IRQn, 10U);
    NVIC_EnableIRQ(CCU40_3_IRQn);
}

static void bms_board_usic_init(void)
{
    /* 启动RS485接收字节中断 */
    XMC_GPIO_SetOutputLow(RS485_Mode_Pin_PORT, RS485_Mode_Pin_PIN); 
    NVIC_SetPriority(RS485_Node_RECEIVE_EVENT_IRQN, 5U);
    NVIC_EnableIRQ(RS485_Node_RECEIVE_EVENT_IRQN);

    /* 启动 HOST UART接收字节中断 */ 
    NVIC_SetPriority(HOST_UART_RECEIVE_EVENT_IRQN, 4U);
    NVIC_EnableIRQ(HOST_UART_RECEIVE_EVENT_IRQN);

    /* 启动WiFi UART接收字节中断 */
    NVIC_SetPriority(WIFI_UART_RECEIVE_EVENT_IRQN, 4U);
    NVIC_DisableIRQ(WIFI_UART_RECEIVE_EVENT_IRQN);
}

static void bms_board_can_init(void)
{
    XMC_CAN_Enable(CAN);
    XMC_CAN_NODE_Enable(CAN_Node_HW);

    NVIC_SetPriority(CAN0_0_IRQn, 6U);
    NVIC_EnableIRQ(CAN0_0_IRQn);
}


static void bms_board_adc_init(void)
{
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 0, 0); // ADC测量NTC2
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 0, 1); // ADC测量电池电压（电池包串联后）
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 0, 2); // ADC测量充电监测引脚电压
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 0, 3); // ADC测量电池动力输出电流

    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 1, 5); // ADC测量板载5V电压
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 1, 6); // ADC测量绝缘电阻对应的电压
    XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, 1, 7); // ADC测量NTC1

    XMC_VADC_GLOBAL_BackgroundTriggerConversion(VADC); // 开启转换
}

/// @brief BMS板上的回路完整性初始化工作，主要是生成PWM信号，并且使能Capture
/// @param  
static void bms_board_HVIL_init(void)
{
    NVIC_SetPriority(CCU40_0_IRQn, 6U);
    NVIC_EnableIRQ(CCU40_0_IRQn);

    NVIC_SetPriority(CCU40_1_IRQn, 6U);
    NVIC_EnableIRQ(CCU40_1_IRQn);
}



int main(void)
{
    fill_stack_with_pattern(); /* 初始化stack，仅为统计RAM使用率 */
    
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    bms_board_HVIL_init(); /* HVIL回路完整性检查初始化 */
    bms_board_tick_init(); /* 初始化系统定时器 */
    bms_board_usic_init(); /* 使用USIC外设前初始化 */
    bms_board_can_init(); /* 使用CAN外设前初始化 */
    bms_board_adc_init(); /* 使用ADC外设前初始化 */
    
    bms_init(); /* BMS初始化 */

    while(1)
    {
        bms_run();
    }

    return 0;
}

/* [] END OF FILE */
